name: Ilk pipeline

#trigger (tetikleyici)
on:
  push: 
    branches: [ "master" ]

jobs:
  docker-login:
    name: Login to docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#Docker hub a login ol
#Not: eger repository olarak docker hub a baglandım

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
   
